### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by p3lim** [canonical/autoinstall-desktop#8]
I have a necessity for making this autoinstall setup work offline. The only part I'd require to do so is by making the `ubuntu-desktop` package (and its dependencies) part of the cdrom source for apt, as well as the snaps. Everything else is available from the ISO already.

How do I go about making this possible?

**Comment by springfielddatarecovery** [comment]
This may be of assistance https://askubuntu.com/questions/1483970/how-to-install-packages-offline-with-ubuntu-22-04-server-autoinstall

**Comment by p3lim** [comment]
With 23.04 (and later) versions of Ubuntu Desktop using autoinstall this is now resolved.
